name: Docker Image CI

on:
  # Schedule the workflow to run at 2:34 AM UTC daily
  #schedule:
  #  - cron: '34 2 * * *'
  push:
    branches: [ "main" ]
    # Optionally, publish semver tags as releases
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use GitHub Container Registry if REGISTRY is empty
  REGISTRY: ghcr.io
  # Use the GitHub repository as the image name
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Needed to complete the identity challenge with sigstore/fulcio outside of PRs
      id-token: write
      
    steps:
    # Step to checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step to extract metadata (tags, labels) for Docker
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    # Step to install the cosign tool except on PRs
    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@v3.5.0
      with:
        cosign-release: 'v2.2.4'

    # Workaround to set up Docker buildx
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
    
    # Step to log into the Docker registry except on PRs
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step to build and push the Docker image with Buildx (don't push on PRs)
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # Step to sign the resulting Docker image digest except on PRs
    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}
      env:
        COSIGN_EXPERIMENTAL: "true"
      # This step uses the identity token to provision an ephemeral certificate against the sigstore community Fulcio instance
      run: cosign sign ${{ steps.meta.outputs.tags }}@${{ steps.build-and-push.outputs.digest }}
      
    # Optional build step (commented out)
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}
